baseUrl = "https://cmgpnotes.cz"
languageCode = "cs-cz"
title = "Cmgp Notes"
defaultContentLanguage = "cz"
[params]
  description = "Sdílení poznámek a zdrojů ke studiu"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[taxonomies]
  topic = "topics"
  author = "authors"
  grade = "grades"
  teacher = "teachers"
